FROM golang:1.23 AS builder
WORKDIR /app

# 先拷贝 go.mod / go.sum，只要依赖不变，就能利用缓存
COPY go.mod go.sum ./
RUN go mod download

# 再拷贝源码，业务改动只会触发编译，不会重新下载依赖
COPY . .
RUN CGO_ENABLED=0 go build -o xgin

FROM scratch
WORKDIR /app
COPY --from=builder /app/xgin ./xgin
CMD ["/app/xgin"]